// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentAutomationRun = "agent_automation_runs"

// AgentAutomationRun mapped from table <agent_automation_runs>
type AgentAutomationRun struct {
	ID          *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID    string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID     string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	Kind        string  `gorm:"column:kind;type:TEXT;not null" json:"kind"`
	ScheduleID  *string `gorm:"column:schedule_id;type:TEXT" json:"schedule_id"`
	SessionID   *string `gorm:"column:session_id;type:TEXT" json:"session_id"`
	CloudRunID  *string `gorm:"column:cloud_run_id;type:TEXT" json:"cloud_run_id"`
	Status      string  `gorm:"column:status;type:TEXT;not null" json:"status"`
	Prompt      *string `gorm:"column:prompt;type:TEXT" json:"prompt"`
	ResultText  *string `gorm:"column:result_text;type:TEXT" json:"result_text"`
	Error       *string `gorm:"column:error;type:TEXT" json:"error"`
	StartedAt   *string `gorm:"column:started_at;type:TEXT" json:"started_at"`
	CompletedAt *string `gorm:"column:completed_at;type:TEXT" json:"completed_at"`
	CreatedAt   string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName AgentAutomationRun's table name
func (*AgentAutomationRun) TableName() string {
	return TableNameAgentAutomationRun
}
