// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentChannelThread = "agent_channel_threads"

// AgentChannelThread mapped from table <agent_channel_threads>
type AgentChannelThread struct {
	ID                *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID          string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	BindingID         string  `gorm:"column:binding_id;type:TEXT;not null" json:"binding_id"`
	SessionID         string  `gorm:"column:session_id;type:TEXT;not null" json:"session_id"`
	ExternalThreadKey string  `gorm:"column:external_thread_key;type:TEXT;not null" json:"external_thread_key"`
	ExternalUserKey   *string `gorm:"column:external_user_key;type:TEXT" json:"external_user_key"`
	LastEventID       *string `gorm:"column:last_event_id;type:TEXT" json:"last_event_id"`
	LastEventAt       *string `gorm:"column:last_event_at;type:TEXT" json:"last_event_at"`
	CreatedAt         string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt         string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName AgentChannelThread's table name
func (*AgentChannelThread) TableName() string {
	return TableNameAgentChannelThread
}
