// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentHeartbeat = "agent_heartbeats"

// AgentHeartbeat mapped from table <agent_heartbeats>
type AgentHeartbeat struct {
	AgentID         *string `gorm:"column:agent_id;type:TEXT;primaryKey" json:"agent_id"`
	TenantID        string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Enabled         bool    `gorm:"column:enabled;type:INTEGER;not null" json:"enabled"`
	IntervalMinutes int32   `gorm:"column:interval_minutes;type:INTEGER;not null;default:60" json:"interval_minutes"`
	Prompt          *string `gorm:"column:prompt;type:TEXT" json:"prompt"`
	NextRunAt       *string `gorm:"column:next_run_at;type:TEXT" json:"next_run_at"`
	LastRunAt       *string `gorm:"column:last_run_at;type:TEXT" json:"last_run_at"`
	LastStatus      *string `gorm:"column:last_status;type:TEXT" json:"last_status"`
	LastError       *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt       string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt       string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName AgentHeartbeat's table name
func (*AgentHeartbeat) TableName() string {
	return TableNameAgentHeartbeat
}
