// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentSkill = "agent_skills"

// AgentSkill mapped from table <agent_skills>
type AgentSkill struct {
	ID        *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID  string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID   string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	SkillID   string  `gorm:"column:skill_id;type:TEXT;not null" json:"skill_id"`
	Name      string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Enabled   bool    `gorm:"column:enabled;type:INTEGER;not null;default:1" json:"enabled"`
	Path      string  `gorm:"column:path;type:TEXT;not null" json:"path"`
	Version   *string `gorm:"column:version;type:TEXT" json:"version"`
	Status    string  `gorm:"column:status;type:TEXT;not null;default:'installed'" json:"status"`
	Error     *string `gorm:"column:error;type:TEXT" json:"error"`
	CreatedAt string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName AgentSkill's table name
func (*AgentSkill) TableName() string {
	return TableNameAgentSkill
}
