// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentChannelBinding = "agent_channel_bindings"

// AgentChannelBinding mapped from table <agent_channel_bindings>
type AgentChannelBinding struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	SpaceID      string  `gorm:"column:space_id;type:TEXT;not null" json:"space_id"`
	AgentID      string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	Platform     string  `gorm:"column:platform;type:TEXT;not null" json:"platform"`
	ProfileKey   string  `gorm:"column:profile_key;type:TEXT;not null" json:"profile_key"`
	Label        string  `gorm:"column:label;type:TEXT;not null" json:"label"`
	Enabled      bool    `gorm:"column:enabled;type:INTEGER;not null" json:"enabled"`
	SettingsJSON string  `gorm:"column:settings_json;type:TEXT;not null;default:'{}'" json:"settings_json"`
	ConfigEnc    string  `gorm:"column:config_enc;type:TEXT;not null" json:"config_enc"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName AgentChannelBinding's table name
func (*AgentChannelBinding) TableName() string {
	return TableNameAgentChannelBinding
}
