// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentUserQuestion = "agent_user_questions"

// AgentUserQuestion mapped from table <agent_user_questions>
type AgentUserQuestion struct {
	ID                   *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID             string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID              string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	SessionID            string  `gorm:"column:session_id;type:TEXT;not null" json:"session_id"`
	RunID                *string `gorm:"column:run_id;type:TEXT" json:"run_id"`
	ToolCallID           *string `gorm:"column:tool_call_id;type:TEXT" json:"tool_call_id"`
	Question             string  `gorm:"column:question;type:TEXT;not null" json:"question"`
	OptionsJSON          string  `gorm:"column:options_json;type:TEXT;not null;default:'[]'" json:"options_json"`
	AllowMultiple        bool    `gorm:"column:allow_multiple;type:INTEGER;not null" json:"allow_multiple"`
	Secret               bool    `gorm:"column:secret;type:INTEGER;not null" json:"secret"`
	Mode                 string  `gorm:"column:mode;type:TEXT;not null;default:'sync'" json:"mode"`
	TimeoutSeconds       *int32  `gorm:"column:timeout_seconds;type:INTEGER" json:"timeout_seconds"`
	TimeoutAction        string  `gorm:"column:timeout_action;type:TEXT;not null;default:'skip'" json:"timeout_action"`
	DefaultOptionIdsJSON string  `gorm:"column:default_option_ids_json;type:TEXT;not null;default:'[]'" json:"default_option_ids_json"`
	Placeholder          string  `gorm:"column:placeholder;type:TEXT;not null" json:"placeholder"`
	Status               string  `gorm:"column:status;type:TEXT;not null;default:'pending'" json:"status"`
	AnswerJSON           string  `gorm:"column:answer_json;type:TEXT;not null;default:'{}'" json:"answer_json"`
	ExpiresAt            *string `gorm:"column:expires_at;type:TEXT" json:"expires_at"`
	ResolvedAt           *string `gorm:"column:resolved_at;type:TEXT" json:"resolved_at"`
	CreatedAt            string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName AgentUserQuestion's table name
func (*AgentUserQuestion) TableName() string {
	return TableNameAgentUserQuestion
}
