// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentConnectorInstallation = "agent_connector_installations"

// AgentConnectorInstallation mapped from table <agent_connector_installations>
type AgentConnectorInstallation struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID      string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	ConnectorRef string  `gorm:"column:connector_ref;type:TEXT;not null" json:"connector_ref"`
	Enabled      bool    `gorm:"column:enabled;type:INTEGER;not null;default:1" json:"enabled"`
	ConfigEnc    string  `gorm:"column:config_enc;type:TEXT;not null" json:"config_enc"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName AgentConnectorInstallation's table name
func (*AgentConnectorInstallation) TableName() string {
	return TableNameAgentConnectorInstallation
}
