// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAuthLoginFailure = "auth_login_failures"

// AuthLoginFailure mapped from table <auth_login_failures>
type AuthLoginFailure struct {
	KeyHash   *string `gorm:"column:key_hash;type:TEXT;primaryKey" json:"key_hash"`
	Count     int32   `gorm:"column:count;type:INTEGER;not null" json:"count"`
	ResetAt   string  `gorm:"column:reset_at;type:TEXT;not null" json:"reset_at"`
	UpdatedAt string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName AuthLoginFailure's table name
func (*AuthLoginFailure) TableName() string {
	return TableNameAuthLoginFailure
}
