// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAuthToken = "auth_tokens"

// AuthToken mapped from table <auth_tokens>
type AuthToken struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	UserID     *string `gorm:"column:user_id;type:TEXT" json:"user_id"`
	Kind       string  `gorm:"column:kind;type:TEXT;not null" json:"kind"`
	TokenHash  string  `gorm:"column:token_hash;type:TEXT;not null" json:"token_hash"`
	MetaJSON   string  `gorm:"column:meta_json;type:TEXT;not null;default:'{}'" json:"meta_json"`
	ExpiresAt  string  `gorm:"column:expires_at;type:TEXT;not null" json:"expires_at"`
	ConsumedAt *string `gorm:"column:consumed_at;type:TEXT" json:"consumed_at"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName AuthToken's table name
func (*AuthToken) TableName() string {
	return TableNameAuthToken
}
