// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameChannelEvent = "channel_events"

// ChannelEvent mapped from table <channel_events>
type ChannelEvent struct {
	ID             *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID       string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Provider       string  `gorm:"column:provider;type:TEXT;not null" json:"provider"`
	ExternalID     string  `gorm:"column:external_id;type:TEXT;not null" json:"external_id"`
	PayloadJSON    string  `gorm:"column:payload_json;type:TEXT;not null" json:"payload_json"`
	DeliveryStatus string  `gorm:"column:delivery_status;type:TEXT;not null;default:'pending'" json:"delivery_status"`
	Attempts       int32   `gorm:"column:attempts;type:INTEGER;not null" json:"attempts"`
	LastError      *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt      string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	ProcessedAt    *string `gorm:"column:processed_at;type:TEXT" json:"processed_at"`
}

// TableName ChannelEvent's table name
func (*ChannelEvent) TableName() string {
	return TableNameChannelEvent
}
