// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCloudAgentRun = "cloud_agent_runs"

// CloudAgentRun mapped from table <cloud_agent_runs>
type CloudAgentRun struct {
	ID              *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	SessionID       string  `gorm:"column:session_id;type:TEXT;not null" json:"session_id"`
	Status          string  `gorm:"column:status;type:TEXT;not null" json:"status"`
	CancelRequested bool    `gorm:"column:cancel_requested;type:INTEGER;not null" json:"cancel_requested"`
	Error           *string `gorm:"column:error;type:TEXT" json:"error"`
	StartedAt       *string `gorm:"column:started_at;type:TEXT" json:"started_at"`
	CompletedAt     *string `gorm:"column:completed_at;type:TEXT" json:"completed_at"`
	CreatedAt       string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName CloudAgentRun's table name
func (*CloudAgentRun) TableName() string {
	return TableNameCloudAgentRun
}
