// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameConnectorAuthProfile = "connector_auth_profiles"

// ConnectorAuthProfile mapped from table <connector_auth_profiles>
type ConnectorAuthProfile struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	ScopeKey   string  `gorm:"column:scope_key;type:TEXT;not null" json:"scope_key"`
	ProfileKey string  `gorm:"column:profile_key;type:TEXT;not null" json:"profile_key"`
	Label      string  `gorm:"column:label;type:TEXT;not null" json:"label"`
	Kind       string  `gorm:"column:kind;type:TEXT;not null" json:"kind"`
	Enabled    bool    `gorm:"column:enabled;type:INTEGER;not null" json:"enabled"`
	ConfigEnc  string  `gorm:"column:config_enc;type:TEXT;not null" json:"config_enc"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt  string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName ConnectorAuthProfile's table name
func (*ConnectorAuthProfile) TableName() string {
	return TableNameConnectorAuthProfile
}
