// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameConnectorSetting = "connector_settings"

// ConnectorSetting mapped from table <connector_settings>
type ConnectorSetting struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	ScopeKey     string  `gorm:"column:scope_key;type:TEXT;not null" json:"scope_key"`
	ConnectorRef string  `gorm:"column:connector_ref;type:TEXT;not null" json:"connector_ref"`
	ConfigEnc    string  `gorm:"column:config_enc;type:TEXT;not null" json:"config_enc"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName ConnectorSetting's table name
func (*ConnectorSetting) TableName() string {
	return TableNameConnectorSetting
}
