// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameFileShare = "file_shares"

// FileShare mapped from table <file_shares>
type FileShare struct {
	ID            *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID      string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID       string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	TokenHash     string  `gorm:"column:token_hash;type:TEXT;not null" json:"token_hash"`
	Path          string  `gorm:"column:path;type:TEXT;not null" json:"path"`
	FileName      string  `gorm:"column:file_name;type:TEXT;not null" json:"file_name"`
	MimeType      *string `gorm:"column:mime_type;type:TEXT" json:"mime_type"`
	SizeBytes     *int32  `gorm:"column:size_bytes;type:INTEGER" json:"size_bytes"`
	Status        string  `gorm:"column:status;type:TEXT;not null;default:'active'" json:"status"`
	TTLMinutes    int32   `gorm:"column:ttl_minutes;type:INTEGER;not null" json:"ttl_minutes"`
	ExpiresAt     string  `gorm:"column:expires_at;type:TEXT;not null" json:"expires_at"`
	DownloadCount int32   `gorm:"column:download_count;type:INTEGER;not null" json:"download_count"`
	Disposition   string  `gorm:"column:disposition;type:TEXT;not null;default:'attachment'" json:"disposition"`
	RevokedAt     *string `gorm:"column:revoked_at;type:TEXT" json:"revoked_at"`
	CreatedAt     string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt     string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName FileShare's table name
func (*FileShare) TableName() string {
	return TableNameFileShare
}
