// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameManagedContainer = "managed_containers"

// ManagedContainer mapped from table <managed_containers>
type ManagedContainer struct {
	ID            *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID      string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	InstanceID    *string `gorm:"column:instance_id;type:TEXT" json:"instance_id"`
	SpaceID       *string `gorm:"column:space_id;type:TEXT" json:"space_id"`
	AgentID       *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	DockerID      *string `gorm:"column:docker_id;type:TEXT" json:"docker_id"`
	Name          string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Image         string  `gorm:"column:image;type:TEXT;not null" json:"image"`
	Purpose       string  `gorm:"column:purpose;type:TEXT;not null;default:'component'" json:"purpose"`
	Status        string  `gorm:"column:status;type:TEXT;not null;default:'created'" json:"status"`
	LabelsJSON    string  `gorm:"column:labels_json;type:TEXT;not null;default:'{}'" json:"labels_json"`
	PortsJSON     string  `gorm:"column:ports_json;type:TEXT;not null;default:'[]'" json:"ports_json"`
	EnvEnc        *string `gorm:"column:env_enc;type:TEXT" json:"env_enc"`
	AllocatedTo   *string `gorm:"column:allocated_to;type:TEXT" json:"allocated_to"`
	RuntimeNodeID *string `gorm:"column:runtime_node_id;type:TEXT" json:"runtime_node_id"`
	CreatedAt     string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt     string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName ManagedContainer's table name
func (*ManagedContainer) TableName() string {
	return TableNameManagedContainer
}
