// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMemory = "memories"

// Memory mapped from table <memories>
type Memory struct {
	ID             *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID       string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	InstanceID     *string `gorm:"column:instance_id;type:TEXT" json:"instance_id"`
	ProviderID     *string `gorm:"column:provider_id;type:TEXT" json:"provider_id"`
	AgentID        *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	UserID         *string `gorm:"column:user_id;type:TEXT" json:"user_id"`
	Layer          string  `gorm:"column:layer;type:TEXT;not null;default:'fact'" json:"layer"`
	Content        string  `gorm:"column:content;type:TEXT;not null" json:"content"`
	TagsJSON       string  `gorm:"column:tags_json;type:TEXT;not null;default:'[]'" json:"tags_json"`
	Pinned         int32   `gorm:"column:pinned;type:INTEGER;not null" json:"pinned"`
	Importance     string  `gorm:"column:importance;type:TEXT;not null;default:'3'" json:"importance"`
	Source         string  `gorm:"column:source;type:TEXT;not null;default:'manual'" json:"source"`
	MetadataJSON   string  `gorm:"column:metadata_json;type:TEXT;not null;default:'{}'" json:"metadata_json"`
	Embedding      *string `gorm:"column:embedding;type:TEXT" json:"embedding"`
	EmbeddingModel *string `gorm:"column:embedding_model;type:TEXT" json:"embedding_model"`
	EmbeddingDim   *int32  `gorm:"column:embedding_dim;type:INTEGER" json:"embedding_dim"`
	ContentHash    *string `gorm:"column:content_hash;type:TEXT" json:"content_hash"`
	CreatedAt      string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt      string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName Memory's table name
func (*Memory) TableName() string {
	return TableNameMemory
}
