// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMessageReaction = "message_reactions"

// MessageReaction mapped from table <message_reactions>
type MessageReaction struct {
	ID        *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID  string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	DeviceID  string  `gorm:"column:device_id;type:TEXT;not null" json:"device_id"`
	BindingID string  `gorm:"column:binding_id;type:TEXT;not null" json:"binding_id"`
	AgentID   string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	MessageID string  `gorm:"column:message_id;type:TEXT;not null" json:"message_id"`
	UserID    string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	Emoji     string  `gorm:"column:emoji;type:TEXT;not null" json:"emoji"`
	CreatedAt string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName MessageReaction's table name
func (*MessageReaction) TableName() string {
	return TableNameMessageReaction
}
