// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameModelCatalogEntry = "model_catalog_entries"

// ModelCatalogEntry mapped from table <model_catalog_entries>
type ModelCatalogEntry struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Source       string  `gorm:"column:source;type:TEXT;not null" json:"source"`
	ProviderID   string  `gorm:"column:provider_id;type:TEXT;not null" json:"provider_id"`
	ProviderName string  `gorm:"column:provider_name;type:TEXT;not null" json:"provider_name"`
	ModelID      string  `gorm:"column:model_id;type:TEXT;not null" json:"model_id"`
	Name         string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	MetaJSON     string  `gorm:"column:meta_json;type:TEXT;not null;default:'{}'" json:"meta_json"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName ModelCatalogEntry's table name
func (*ModelCatalogEntry) TableName() string {
	return TableNameModelCatalogEntry
}
