// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameModelRoute = "model_routes"

// ModelRoute mapped from table <model_routes>
type ModelRoute struct {
	ID          *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID    string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Name        string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Slug        string  `gorm:"column:slug;type:TEXT;not null" json:"slug"`
	Capability  string  `gorm:"column:capability;type:TEXT;not null" json:"capability"`
	Alias       *string `gorm:"column:alias;type:TEXT" json:"alias"`
	UpstreamID  string  `gorm:"column:upstream_id;type:TEXT;not null" json:"upstream_id"`
	Model       string  `gorm:"column:model;type:TEXT;not null" json:"model"`
	OptionsJSON string  `gorm:"column:options_json;type:TEXT;not null;default:'{}'" json:"options_json"`
	Priority    string  `gorm:"column:priority;type:TEXT;not null;default:'100'" json:"priority"`
	Weight      string  `gorm:"column:weight;type:TEXT;not null;default:'100'" json:"weight"`
	IsDefault   bool    `gorm:"column:is_default;type:INTEGER;not null" json:"is_default"`
	Status      string  `gorm:"column:status;type:TEXT;not null;default:'ready'" json:"status"`
	LastError   *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt   string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt   string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName ModelRoute's table name
func (*ModelRoute) TableName() string {
	return TableNameModelRoute
}
