// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOauthAuthCode = "oauth_auth_codes"

// OauthAuthCode mapped from table <oauth_auth_codes>
type OauthAuthCode struct {
	ID                  *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	CodeHash            string  `gorm:"column:code_hash;type:TEXT;not null" json:"code_hash"`
	ClientID            string  `gorm:"column:client_id;type:TEXT;not null" json:"client_id"`
	UserID              string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	TenantID            string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID             *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	RedirectURI         string  `gorm:"column:redirect_uri;type:TEXT;not null" json:"redirect_uri"`
	Scope               string  `gorm:"column:scope;type:TEXT;not null" json:"scope"`
	Resource            *string `gorm:"column:resource;type:TEXT" json:"resource"`
	CodeChallenge       *string `gorm:"column:code_challenge;type:TEXT" json:"code_challenge"`
	CodeChallengeMethod *string `gorm:"column:code_challenge_method;type:TEXT" json:"code_challenge_method"`
	ExpiresAt           string  `gorm:"column:expires_at;type:TEXT;not null" json:"expires_at"`
	UsedAt              *string `gorm:"column:used_at;type:TEXT" json:"used_at"`
	CreatedAt           string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName OauthAuthCode's table name
func (*OauthAuthCode) TableName() string {
	return TableNameOauthAuthCode
}
