// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOauthClient = "oauth_clients"

// OauthClient mapped from table <oauth_clients>
type OauthClient struct {
	ID                      *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID                *string `gorm:"column:tenant_id;type:TEXT" json:"tenant_id"`
	ClientID                string  `gorm:"column:client_id;type:TEXT;not null" json:"client_id"`
	ClientSecretHash        *string `gorm:"column:client_secret_hash;type:TEXT" json:"client_secret_hash"`
	ClientName              string  `gorm:"column:client_name;type:TEXT;not null" json:"client_name"`
	RedirectUrisJSON        string  `gorm:"column:redirect_uris_json;type:TEXT;not null" json:"redirect_uris_json"`
	GrantTypesJSON          string  `gorm:"column:grant_types_json;type:TEXT;not null" json:"grant_types_json"`
	ResponseTypesJSON       string  `gorm:"column:response_types_json;type:TEXT;not null" json:"response_types_json"`
	TokenEndpointAuthMethod string  `gorm:"column:token_endpoint_auth_method;type:TEXT;not null" json:"token_endpoint_auth_method"`
	Scope                   string  `gorm:"column:scope;type:TEXT;not null;default:'mcp'" json:"scope"`
	RegistrationType        string  `gorm:"column:registration_type;type:TEXT;not null;default:'dynamic'" json:"registration_type"`
	CreatedAt               string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt               string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName OauthClient's table name
func (*OauthClient) TableName() string {
	return TableNameOauthClient
}
