// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePlatformMetum = "platform_meta"

// PlatformMetum mapped from table <platform_meta>
type PlatformMetum struct {
	Singleton      *int32 `gorm:"column:singleton;type:INTEGER;primaryKey" json:"singleton"`
	SetupCompleted bool   `gorm:"column:setup_completed;type:INTEGER;not null" json:"setup_completed"`
	Version        string `gorm:"column:version;type:TEXT;not null;default:'go-rewrite'" json:"version"`
	Mode           string `gorm:"column:mode;type:TEXT;not null;default:'local'" json:"mode"`
	SettingsJSON   string `gorm:"column:settings_json;type:TEXT;not null;default:'{}'" json:"settings_json"`
	CreatedAt      string `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt      string `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName PlatformMetum's table name
func (*PlatformMetum) TableName() string {
	return TableNamePlatformMetum
}
