// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePlatformService = "platform_services"

// PlatformService mapped from table <platform_services>
type PlatformService struct {
	ID             *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	ServiceKey     string  `gorm:"column:service_key;type:TEXT;not null" json:"service_key"`
	Mode           string  `gorm:"column:mode;type:TEXT;not null;default:'disabled'" json:"mode"`
	DesiredState   string  `gorm:"column:desired_state;type:TEXT;not null;default:'stopped'" json:"desired_state"`
	Status         string  `gorm:"column:status;type:TEXT;not null;default:'stopped'" json:"status"`
	HealthStatus   string  `gorm:"column:health_status;type:TEXT;not null;default:'unknown'" json:"health_status"`
	ConfigEnc      string  `gorm:"column:config_enc;type:TEXT;not null;default:'{}'" json:"config_enc"`
	EndpointURL    *string `gorm:"column:endpoint_url;type:TEXT" json:"endpoint_url"`
	ContainersJSON string  `gorm:"column:containers_json;type:TEXT;not null;default:'[]'" json:"containers_json"`
	LastError      *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt      string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt      string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName PlatformService's table name
func (*PlatformService) TableName() string {
	return TableNamePlatformService
}
