// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSchemaMigration = "schema_migrations"

// SchemaMigration mapped from table <schema_migrations>
type SchemaMigration struct {
	Version   *int32 `gorm:"column:version;type:INTEGER;primaryKey" json:"version"`
	Name      string `gorm:"column:name;type:TEXT;not null" json:"name"`
	AppliedAt string `gorm:"column:applied_at;type:TEXT;not null" json:"applied_at"`
}

// TableName SchemaMigration's table name
func (*SchemaMigration) TableName() string {
	return TableNameSchemaMigration
}
