// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameScimUserMapping = "scim_user_mappings"

// ScimUserMapping mapped from table <scim_user_mappings>
type ScimUserMapping struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID   string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	UserID     string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	ExternalID string  `gorm:"column:external_id;type:TEXT;not null" json:"external_id"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName ScimUserMapping's table name
func (*ScimUserMapping) TableName() string {
	return TableNameScimUserMapping
}
