// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSkillSourceToken = "skill_source_tokens"

// SkillSourceToken mapped from table <skill_source_tokens>
type SkillSourceToken struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	ScopeKey   string  `gorm:"column:scope_key;type:TEXT;not null" json:"scope_key"`
	Provider   string  `gorm:"column:provider;type:TEXT;not null;default:'github'" json:"provider"`
	TokenEnc   string  `gorm:"column:token_enc;type:TEXT;not null" json:"token_enc"`
	Label      *string `gorm:"column:label;type:TEXT" json:"label"`
	Hint       *string `gorm:"column:hint;type:TEXT" json:"hint"`
	LastUsedAt *string `gorm:"column:last_used_at;type:TEXT" json:"last_used_at"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt  string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName SkillSourceToken's table name
func (*SkillSourceToken) TableName() string {
	return TableNameSkillSourceToken
}
