// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSpaceProject = "space_projects"

// SpaceProject mapped from table <space_projects>
type SpaceProject struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	SpaceID      string  `gorm:"column:space_id;type:TEXT;not null" json:"space_id"`
	Slug         string  `gorm:"column:slug;type:TEXT;not null" json:"slug"`
	Name         string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Description  string  `gorm:"column:description;type:TEXT;not null" json:"description"`
	Instructions string  `gorm:"column:instructions;type:TEXT;not null" json:"instructions"`
	HasWorkspace bool    `gorm:"column:has_workspace;type:INTEGER;not null" json:"has_workspace"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName SpaceProject's table name
func (*SpaceProject) TableName() string {
	return TableNameSpaceProject
}
