// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSsoLoginState = "sso_login_states"

// SsoLoginState mapped from table <sso_login_states>
type SsoLoginState struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Protocol     string  `gorm:"column:protocol;type:TEXT;not null" json:"protocol"`
	CodeVerifier *string `gorm:"column:code_verifier;type:TEXT" json:"code_verifier"`
	Nonce        *string `gorm:"column:nonce;type:TEXT" json:"nonce"`
	ExpiresAt    string  `gorm:"column:expires_at;type:TEXT;not null" json:"expires_at"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName SsoLoginState's table name
func (*SsoLoginState) TableName() string {
	return TableNameSsoLoginState
}
