// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTenantContentCleanupJob = "tenant_content_cleanup_jobs"

// TenantContentCleanupJob mapped from table <tenant_content_cleanup_jobs>
type TenantContentCleanupJob struct {
	ID             *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	IdempotencyKey string  `gorm:"column:idempotency_key;type:TEXT;not null" json:"idempotency_key"`
	TenantID       string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Action         string  `gorm:"column:action;type:TEXT;not null" json:"action"`
	PayloadJSON    string  `gorm:"column:payload_json;type:TEXT;not null;default:'{}'" json:"payload_json"`
	Status         string  `gorm:"column:status;type:TEXT;not null;default:'pending'" json:"status"`
	Attempts       int32   `gorm:"column:attempts;type:INTEGER;not null" json:"attempts"`
	MaxAttempts    int32   `gorm:"column:max_attempts;type:INTEGER;not null;default:8" json:"max_attempts"`
	AvailableAt    string  `gorm:"column:available_at;type:TEXT;not null" json:"available_at"`
	LockedAt       *string `gorm:"column:locked_at;type:TEXT" json:"locked_at"`
	LockedBy       *string `gorm:"column:locked_by;type:TEXT" json:"locked_by"`
	LastError      *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CompletedAt    *string `gorm:"column:completed_at;type:TEXT" json:"completed_at"`
	CreatedAt      string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt      string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName TenantContentCleanupJob's table name
func (*TenantContentCleanupJob) TableName() string {
	return TableNameTenantContentCleanupJob
}
