// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTenantSsoConfig = "tenant_sso_configs"

// TenantSsoConfig mapped from table <tenant_sso_configs>
type TenantSsoConfig struct {
	ID                *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID          string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Protocol          string  `gorm:"column:protocol;type:TEXT;not null" json:"protocol"`
	Enabled           bool    `gorm:"column:enabled;type:INTEGER;not null" json:"enabled"`
	Issuer            *string `gorm:"column:issuer;type:TEXT" json:"issuer"`
	ClientID          *string `gorm:"column:client_id;type:TEXT" json:"client_id"`
	ClientSecretEnc   *string `gorm:"column:client_secret_enc;type:TEXT" json:"client_secret_enc"`
	AuthorizeURL      *string `gorm:"column:authorize_url;type:TEXT" json:"authorize_url"`
	TokenURL          *string `gorm:"column:token_url;type:TEXT" json:"token_url"`
	JwksURL           *string `gorm:"column:jwks_url;type:TEXT" json:"jwks_url"`
	UserinfoURL       *string `gorm:"column:userinfo_url;type:TEXT" json:"userinfo_url"`
	Scopes            string  `gorm:"column:scopes;type:TEXT;not null;default:'openid email profile'" json:"scopes"`
	IdpEntityID       *string `gorm:"column:idp_entity_id;type:TEXT" json:"idp_entity_id"`
	IdpSsoURL         *string `gorm:"column:idp_sso_url;type:TEXT" json:"idp_sso_url"`
	IdpCertificateEnc *string `gorm:"column:idp_certificate_enc;type:TEXT" json:"idp_certificate_enc"`
	JitEnabled        bool    `gorm:"column:jit_enabled;type:INTEGER;not null;default:1" json:"jit_enabled"`
	EnforceSso        bool    `gorm:"column:enforce_sso;type:INTEGER;not null" json:"enforce_sso"`
	DefaultRole       string  `gorm:"column:default_role;type:TEXT;not null;default:'member'" json:"default_role"`
	ConfigJSON        string  `gorm:"column:config_json;type:TEXT;not null;default:'{}'" json:"config_json"`
	SecretJSON        string  `gorm:"column:secret_json;type:TEXT;not null;default:'{}'" json:"secret_json"`
	CreatedAt         string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt         string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName TenantSsoConfig's table name
func (*TenantSsoConfig) TableName() string {
	return TableNameTenantSsoConfig
}
