// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTenant = "tenants"

// Tenant mapped from table <tenants>
type Tenant struct {
	ID                  *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	Slug                string  `gorm:"column:slug;type:TEXT;not null" json:"slug"`
	Name                string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	IsDefault           bool    `gorm:"column:is_default;type:INTEGER;not null" json:"is_default"`
	OnboardingCompleted bool    `gorm:"column:onboarding_completed;type:INTEGER;not null" json:"onboarding_completed"`
	OnboardingSteps     string  `gorm:"column:onboarding_steps;type:TEXT;not null;default:'{}'" json:"onboarding_steps"`
	MfaPolicy           string  `gorm:"column:mfa_policy;type:TEXT;not null;default:'optional'" json:"mfa_policy"`
	AuditRetentionDays  int32   `gorm:"column:audit_retention_days;type:INTEGER;not null;default:365" json:"audit_retention_days"`
	SettingsJSON        string  `gorm:"column:settings_json;type:TEXT;not null;default:'{}'" json:"settings_json"`
	Status              string  `gorm:"column:status;type:TEXT;not null;default:'active'" json:"status"`
	SuspendedAt         *string `gorm:"column:suspended_at;type:TEXT" json:"suspended_at"`
	SuspendedReason     *string `gorm:"column:suspended_reason;type:TEXT" json:"suspended_reason"`
	SuspendedByUserID   *string `gorm:"column:suspended_by_user_id;type:TEXT" json:"suspended_by_user_id"`
	CreatedAt           string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt           string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName Tenant's table name
func (*Tenant) TableName() string {
	return TableNameTenant
}
