// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameToolCallLog = "tool_call_logs"

// ToolCallLog mapped from table <tool_call_logs>
type ToolCallLog struct {
	ID            *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID      string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	APIKeyID      *string `gorm:"column:api_key_id;type:TEXT" json:"api_key_id"`
	AgentID       *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	QualifiedName string  `gorm:"column:qualified_name;type:TEXT;not null" json:"qualified_name"`
	LocalName     string  `gorm:"column:local_name;type:TEXT;not null" json:"local_name"`
	ProviderID    string  `gorm:"column:provider_id;type:TEXT;not null" json:"provider_id"`
	InstanceID    *string `gorm:"column:instance_id;type:TEXT" json:"instance_id"`
	ArgsJSON      string  `gorm:"column:args_json;type:TEXT;not null;default:'{}'" json:"args_json"`
	ResultJSON    string  `gorm:"column:result_json;type:TEXT;not null" json:"result_json"`
	IsError       bool    `gorm:"column:is_error;type:INTEGER;not null" json:"is_error"`
	DurationMs    int32   `gorm:"column:duration_ms;type:INTEGER;not null" json:"duration_ms"`
	CreatedAt     string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName ToolCallLog's table name
func (*ToolCallLog) TableName() string {
	return TableNameToolCallLog
}
