// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTunnelProviderSetting = "tunnel_provider_settings"

// TunnelProviderSetting mapped from table <tunnel_provider_settings>
type TunnelProviderSetting struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID   string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Provider   string  `gorm:"column:provider;type:TEXT;not null" json:"provider"`
	Enabled    bool    `gorm:"column:enabled;type:INTEGER;not null" json:"enabled"`
	IsDefault  bool    `gorm:"column:is_default;type:INTEGER;not null" json:"is_default"`
	ConfigEnc  string  `gorm:"column:config_enc;type:TEXT;not null;default:'{}'" json:"config_enc"`
	LastTestAt *string `gorm:"column:last_test_at;type:TEXT" json:"last_test_at"`
	LastTestOk *bool   `gorm:"column:last_test_ok;type:INTEGER" json:"last_test_ok"`
	LastError  *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt  string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName TunnelProviderSetting's table name
func (*TunnelProviderSetting) TableName() string {
	return TableNameTunnelProviderSetting
}
