// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	Email             string  `gorm:"column:email;type:TEXT;not null" json:"email"`
	PasswordHash      *string `gorm:"column:password_hash;type:TEXT" json:"password_hash"`
	Name              *string `gorm:"column:name;type:TEXT" json:"name"`
	Title             *string `gorm:"column:title;type:TEXT" json:"title"`
	Bio               *string `gorm:"column:bio;type:TEXT" json:"bio"`
	AvatarMime        *string `gorm:"column:avatar_mime;type:TEXT" json:"avatar_mime"`
	AvatarData        *[]byte `gorm:"column:avatar_data;type:BLOB" json:"avatar_data"`
	AvatarUpdatedAt   *string `gorm:"column:avatar_updated_at;type:TEXT" json:"avatar_updated_at"`
	EmailVerifiedAt   *string `gorm:"column:email_verified_at;type:TEXT" json:"email_verified_at"`
	TotpSecret        *string `gorm:"column:totp_secret;type:TEXT" json:"totp_secret"`
	TotpPendingSecret *string `gorm:"column:totp_pending_secret;type:TEXT" json:"totp_pending_secret"`
	TotpEnabledAt     *string `gorm:"column:totp_enabled_at;type:TEXT" json:"totp_enabled_at"`
	RecoveryCodesJSON string  `gorm:"column:recovery_codes_json;type:TEXT;not null;default:'[]'" json:"recovery_codes_json"`
	IsPlatformAdmin   bool    `gorm:"column:is_platform_admin;type:INTEGER;not null" json:"is_platform_admin"`
	CanUseLocalRunner bool    `gorm:"column:can_use_local_runner;type:INTEGER;not null" json:"can_use_local_runner"`
	Status            string  `gorm:"column:status;type:TEXT;not null;default:'active'" json:"status"`
	SuspendedAt       *string `gorm:"column:suspended_at;type:TEXT" json:"suspended_at"`
	SuspendedReason   *string `gorm:"column:suspended_reason;type:TEXT" json:"suspended_reason"`
	SuspendedByUserID *string `gorm:"column:suspended_by_user_id;type:TEXT" json:"suspended_by_user_id"`
	LastLoginAt       *string `gorm:"column:last_login_at;type:TEXT" json:"last_login_at"`
	CreatedAt         string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt         string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
