// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserWebauthnCredential = "user_webauthn_credentials"

// UserWebauthnCredential mapped from table <user_webauthn_credentials>
type UserWebauthnCredential struct {
	ID             *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	UserID         string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	Name           *string `gorm:"column:name;type:TEXT" json:"name"`
	CredentialID   string  `gorm:"column:credential_id;type:TEXT;not null" json:"credential_id"`
	PublicKey      string  `gorm:"column:public_key;type:TEXT;not null" json:"public_key"`
	Counter        int32   `gorm:"column:counter;type:INTEGER;not null" json:"counter"`
	TransportsJSON string  `gorm:"column:transports_json;type:TEXT;not null;default:'[]'" json:"transports_json"`
	CreatedAt      string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName UserWebauthnCredential's table name
func (*UserWebauthnCredential) TableName() string {
	return TableNameUserWebauthnCredential
}
