// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameWorkspaceMigration = "workspace_migrations"

// WorkspaceMigration mapped from table <workspace_migrations>
type WorkspaceMigration struct {
	ID                  *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID            string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	SpaceID             string  `gorm:"column:space_id;type:TEXT;not null" json:"space_id"`
	SourceNodeID        string  `gorm:"column:source_node_id;type:TEXT;not null" json:"source_node_id"`
	TargetNodeID        string  `gorm:"column:target_node_id;type:TEXT;not null" json:"target_node_id"`
	Status              string  `gorm:"column:status;type:TEXT;not null;default:'pending'" json:"status"`
	Phase               *string `gorm:"column:phase;type:TEXT" json:"phase"`
	ProgressPct         int32   `gorm:"column:progress_pct;type:INTEGER;not null" json:"progress_pct"`
	Message             *string `gorm:"column:message;type:TEXT" json:"message"`
	ManifestJSON        *string `gorm:"column:manifest_json;type:TEXT" json:"manifest_json"`
	ArchivePath         *string `gorm:"column:archive_path;type:TEXT" json:"archive_path"`
	ArchiveSize         *string `gorm:"column:archive_size;type:TEXT" json:"archive_size"`
	ArchiveSha256       *string `gorm:"column:archive_sha256;type:TEXT" json:"archive_sha256"`
	ExcludePatternsJSON string  `gorm:"column:exclude_patterns_json;type:TEXT;not null;default:'[]'" json:"exclude_patterns_json"`
	SourceRetained      bool    `gorm:"column:source_retained;type:INTEGER;not null" json:"source_retained"`
	Error               *string `gorm:"column:error;type:TEXT" json:"error"`
	StartedAt           *string `gorm:"column:started_at;type:TEXT" json:"started_at"`
	CompletedAt         *string `gorm:"column:completed_at;type:TEXT" json:"completed_at"`
	CreatedAt           string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt           string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName WorkspaceMigration's table name
func (*WorkspaceMigration) TableName() string {
	return TableNameWorkspaceMigration
}
