// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameZakurabotFile = "zakurabot_files"

// ZakurabotFile mapped from table <zakurabot_files>
type ZakurabotFile struct {
	ID        *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID  string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	DeviceID  string  `gorm:"column:device_id;type:TEXT;not null" json:"device_id"`
	BindingID string  `gorm:"column:binding_id;type:TEXT;not null" json:"binding_id"`
	AgentID   string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	Path      string  `gorm:"column:path;type:TEXT;not null" json:"path"`
	Name      string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Mime      string  `gorm:"column:mime;type:TEXT;not null" json:"mime"`
	Size      int32   `gorm:"column:size;type:INTEGER;not null" json:"size"`
	CreatedAt string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName ZakurabotFile's table name
func (*ZakurabotFile) TableName() string {
	return TableNameZakurabotFile
}
