// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameZakurabotMessage = "zakurabot_messages"

// ZakurabotMessage mapped from table <zakurabot_messages>
type ZakurabotMessage struct {
	ID              *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	Seq             int32   `gorm:"column:seq;type:INTEGER;not null" json:"seq"`
	TenantID        string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	DeviceID        string  `gorm:"column:device_id;type:TEXT;not null" json:"device_id"`
	BindingID       string  `gorm:"column:binding_id;type:TEXT;not null" json:"binding_id"`
	AgentID         string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	ClientMessageID *string `gorm:"column:client_message_id;type:TEXT" json:"client_message_id"`
	FrameJSON       string  `gorm:"column:frame_json;type:TEXT;not null" json:"frame_json"`
	CreatedAt       string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName ZakurabotMessage's table name
func (*ZakurabotMessage) TableName() string {
	return TableNameZakurabotMessage
}
