// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentSchedule = "agent_schedules"

// AgentSchedule mapped from table <agent_schedules>
type AgentSchedule struct {
	ID            *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID      string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID       string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	Name          string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Description   *string `gorm:"column:description;type:TEXT" json:"description"`
	Pattern       *string `gorm:"column:pattern;type:TEXT" json:"pattern"`
	TriggerKind   string  `gorm:"column:trigger_kind;type:TEXT;not null;default:'schedule'" json:"trigger_kind"`
	ListenerJSON  string  `gorm:"column:listener_json;type:TEXT;not null;default:'{}'" json:"listener_json"`
	WebhookSecret *string `gorm:"column:webhook_secret;type:TEXT" json:"webhook_secret"`
	Prompt        string  `gorm:"column:prompt;type:TEXT;not null" json:"prompt"`
	Project       *string `gorm:"column:project;type:TEXT" json:"project"`
	Enabled       bool    `gorm:"column:enabled;type:INTEGER;not null;default:1" json:"enabled"`
	MaxRuns       *int32  `gorm:"column:max_runs;type:INTEGER" json:"max_runs"`
	RunCount      int32   `gorm:"column:run_count;type:INTEGER;not null" json:"run_count"`
	Timezone      string  `gorm:"column:timezone;type:TEXT;not null;default:'UTC'" json:"timezone"`
	NextRunAt     *string `gorm:"column:next_run_at;type:TEXT" json:"next_run_at"`
	LastRunAt     *string `gorm:"column:last_run_at;type:TEXT" json:"last_run_at"`
	LastStatus    *string `gorm:"column:last_status;type:TEXT" json:"last_status"`
	LastError     *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt     string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt     string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName AgentSchedule's table name
func (*AgentSchedule) TableName() string {
	return TableNameAgentSchedule
}
