// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentToolApproval = "agent_tool_approvals"

// AgentToolApproval mapped from table <agent_tool_approvals>
type AgentToolApproval struct {
	ID            *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID      string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID       string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	SessionID     string  `gorm:"column:session_id;type:TEXT;not null" json:"session_id"`
	RunID         *string `gorm:"column:run_id;type:TEXT" json:"run_id"`
	ToolCallID    *string `gorm:"column:tool_call_id;type:TEXT" json:"tool_call_id"`
	ToolName      string  `gorm:"column:tool_name;type:TEXT;not null" json:"tool_name"`
	QualifiedName *string `gorm:"column:qualified_name;type:TEXT" json:"qualified_name"`
	ArgsJSON      string  `gorm:"column:args_json;type:TEXT;not null;default:'{}'" json:"args_json"`
	Reason        string  `gorm:"column:reason;type:TEXT;not null;default:'policy_ask'" json:"reason"`
	AiJSON        string  `gorm:"column:ai_json;type:TEXT;not null;default:'{}'" json:"ai_json"`
	Status        string  `gorm:"column:status;type:TEXT;not null;default:'pending'" json:"status"`
	DecidedBy     *string `gorm:"column:decided_by;type:TEXT" json:"decided_by"`
	AlwaysAllow   bool    `gorm:"column:always_allow;type:INTEGER;not null" json:"always_allow"`
	ExpiresAt     *string `gorm:"column:expires_at;type:TEXT" json:"expires_at"`
	ResolvedAt    *string `gorm:"column:resolved_at;type:TEXT" json:"resolved_at"`
	CreatedAt     string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName AgentToolApproval's table name
func (*AgentToolApproval) TableName() string {
	return TableNameAgentToolApproval
}
