// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentBinding = "agent_bindings"

// AgentBinding mapped from table <agent_bindings>
type AgentBinding struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID   string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	SpaceID    string  `gorm:"column:space_id;type:TEXT;not null" json:"space_id"`
	AgentID    *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	InstanceID string  `gorm:"column:instance_id;type:TEXT;not null" json:"instance_id"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName AgentBinding's table name
func (*AgentBinding) TableName() string {
	return TableNameAgentBinding
}
