// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgent = "agents"

// Agent mapped from table <agents>
type Agent struct {
	ID               *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID         string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	SpaceID          string  `gorm:"column:space_id;type:TEXT;not null" json:"space_id"`
	Name             string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Slug             string  `gorm:"column:slug;type:TEXT;not null" json:"slug"`
	Description      string  `gorm:"column:description;type:TEXT;not null" json:"description"`
	EnableMemory     bool    `gorm:"column:enable_memory;type:INTEGER;not null;default:1" json:"enable_memory"`
	MemoryProviderID *string `gorm:"column:memory_provider_id;type:TEXT" json:"memory_provider_id"`
	ConfigJSON       string  `gorm:"column:config_json;type:TEXT;not null;default:'{}'" json:"config_json"`
	LastError        *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	AvatarColor      *string `gorm:"column:avatar_color;type:TEXT" json:"avatar_color"`
	AvatarShape      *string `gorm:"column:avatar_shape;type:TEXT" json:"avatar_shape"`
	AvatarURL        *string `gorm:"column:avatar_url;type:TEXT" json:"avatar_url"`
	CreatedAt        string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt        string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName Agent's table name
func (*Agent) TableName() string {
	return TableNameAgent
}
