// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAgentChannelEvent = "agent_channel_events"

// AgentChannelEvent mapped from table <agent_channel_events>
type AgentChannelEvent struct {
	ID              *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID        string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	BindingID       string  `gorm:"column:binding_id;type:TEXT;not null" json:"binding_id"`
	ExternalEventID string  `gorm:"column:external_event_id;type:TEXT;not null" json:"external_event_id"`
	ReceivedAt      string  `gorm:"column:received_at;type:TEXT;not null" json:"received_at"`
}

// TableName AgentChannelEvent's table name
func (*AgentChannelEvent) TableName() string {
	return TableNameAgentChannelEvent
}
