// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAPIKey = "api_keys"

// APIKey mapped from table <api_keys>
type APIKey struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID   string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	UserID     *string `gorm:"column:user_id;type:TEXT" json:"user_id"`
	AgentID    *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	SpaceID    *string `gorm:"column:space_id;type:TEXT" json:"space_id"`
	Name       string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	KeyPrefix  string  `gorm:"column:key_prefix;type:TEXT;not null" json:"key_prefix"`
	KeyHash    string  `gorm:"column:key_hash;type:TEXT;not null" json:"key_hash"`
	Scopes     string  `gorm:"column:scopes;type:TEXT;not null" json:"scopes"`
	ExpiresAt  *string `gorm:"column:expires_at;type:TEXT" json:"expires_at"`
	LastUsedAt *string `gorm:"column:last_used_at;type:TEXT" json:"last_used_at"`
	RevokedAt  *string `gorm:"column:revoked_at;type:TEXT" json:"revoked_at"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName APIKey's table name
func (*APIKey) TableName() string {
	return TableNameAPIKey
}
