// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCloudAgentSession = "cloud_agent_sessions"

// CloudAgentSession mapped from table <cloud_agent_sessions>
type CloudAgentSession struct {
	ID              *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID        string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID         string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	Title           string  `gorm:"column:title;type:TEXT;not null;default:'新对话'" json:"title"`
	Status          string  `gorm:"column:status;type:TEXT;not null;default:'active'" json:"status"`
	Kind            string  `gorm:"column:kind;type:TEXT;not null;default:'chat'" json:"kind"`
	Project         *string `gorm:"column:project;type:TEXT" json:"project"`
	OriginJSON      string  `gorm:"column:origin_json;type:TEXT;not null;default:'{}'" json:"origin_json"`
	Model           *string `gorm:"column:model;type:TEXT" json:"model"`
	ModelRouteID    *string `gorm:"column:model_route_id;type:TEXT" json:"model_route_id"`
	Reasoning       *string `gorm:"column:reasoning;type:TEXT" json:"reasoning"`
	DraftText       string  `gorm:"column:draft_text;type:TEXT;not null" json:"draft_text"`
	CreatedByUserID *string `gorm:"column:created_by_user_id;type:TEXT" json:"created_by_user_id"`
	LastSeq         int32   `gorm:"column:last_seq;type:INTEGER;not null" json:"last_seq"`
	ActiveRunID     *string `gorm:"column:active_run_id;type:TEXT" json:"active_run_id"`
	CreatedAt       string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt       string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName CloudAgentSession's table name
func (*CloudAgentSession) TableName() string {
	return TableNameCloudAgentSession
}
