// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCloudAgentEvent = "cloud_agent_events"

// CloudAgentEvent mapped from table <cloud_agent_events>
type CloudAgentEvent struct {
	ID          *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	SessionID   string  `gorm:"column:session_id;type:TEXT;not null" json:"session_id"`
	Seq         int32   `gorm:"column:seq;type:INTEGER;not null" json:"seq"`
	Type        string  `gorm:"column:type;type:TEXT;not null" json:"type"`
	RunID       *string `gorm:"column:run_id;type:TEXT" json:"run_id"`
	PayloadJSON string  `gorm:"column:payload_json;type:TEXT;not null;default:'{}'" json:"payload_json"`
	CreatedAt   string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName CloudAgentEvent's table name
func (*CloudAgentEvent) TableName() string {
	return TableNameCloudAgentEvent
}
