// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameComponentInstance = "component_instances"

// ComponentInstance mapped from table <component_instances>
type ComponentInstance struct {
	ID            *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID      string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID       *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	ComponentType string  `gorm:"column:component_type;type:TEXT;not null" json:"component_type"`
	ComponentRef  string  `gorm:"column:component_ref;type:TEXT;not null" json:"component_ref"`
	Name          string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	ConfigJSON    string  `gorm:"column:config_json;type:TEXT;not null;default:'{}'" json:"config_json"`
	SecretJSON    string  `gorm:"column:secret_json;type:TEXT;not null;default:'{}'" json:"secret_json"`
	Status        string  `gorm:"column:status;type:TEXT;not null;default:'ready'" json:"status"`
	LastError     *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt     string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt     string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName ComponentInstance's table name
func (*ComponentInstance) TableName() string {
	return TableNameComponentInstance
}
