// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameEmailConnectorInstance = "email_connector_instances"

// EmailConnectorInstance mapped from table <email_connector_instances>
type EmailConnectorInstance struct {
	ID        *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID  string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Name      string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Product   string  `gorm:"column:product;type:TEXT;not null" json:"product"`
	Enabled   bool    `gorm:"column:enabled;type:INTEGER;not null" json:"enabled"`
	ConfigEnc string  `gorm:"column:config_enc;type:TEXT;not null" json:"config_enc"`
	CreatedAt string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName EmailConnectorInstance's table name
func (*EmailConnectorInstance) TableName() string {
	return TableNameEmailConnectorInstance
}
