// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameIntegrationPackage = "integration_packages"

// IntegrationPackage mapped from table <integration_packages>
type IntegrationPackage struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	Slug         string  `gorm:"column:slug;type:TEXT;not null" json:"slug"`
	Name         string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Description  *string `gorm:"column:description;type:TEXT" json:"description"`
	ManifestJSON string  `gorm:"column:manifest_json;type:TEXT;not null;default:'{}'" json:"manifest_json"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName IntegrationPackage's table name
func (*IntegrationPackage) TableName() string {
	return TableNameIntegrationPackage
}
