// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameIntegrationComponent = "integration_components"

// IntegrationComponent mapped from table <integration_components>
type IntegrationComponent struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	PackageID    string  `gorm:"column:package_id;type:TEXT;not null" json:"package_id"`
	Ref          string  `gorm:"column:ref;type:TEXT;not null" json:"ref"`
	Kind         string  `gorm:"column:kind;type:TEXT;not null" json:"kind"`
	ManifestJSON string  `gorm:"column:manifest_json;type:TEXT;not null;default:'{}'" json:"manifest_json"`
}

// TableName IntegrationComponent's table name
func (*IntegrationComponent) TableName() string {
	return TableNameIntegrationComponent
}
