// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMcpStoreSource = "mcp_store_sources"

// McpStoreSource mapped from table <mcp_store_sources>
type McpStoreSource struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Name         string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Description  string  `gorm:"column:description;type:TEXT;not null" json:"description"`
	SourceURL    string  `gorm:"column:source_url;type:TEXT;not null" json:"source_url"`
	Format       string  `gorm:"column:format;type:TEXT;not null;default:'auto'" json:"format"`
	ManifestJSON string  `gorm:"column:manifest_json;type:TEXT;not null;default:'{}'" json:"manifest_json"`
	ServersJSON  string  `gorm:"column:servers_json;type:TEXT;not null;default:'[]'" json:"servers_json"`
	Enabled      bool    `gorm:"column:enabled;type:INTEGER;not null;default:1" json:"enabled"`
	FetchedAt    *string `gorm:"column:fetched_at;type:TEXT" json:"fetched_at"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName McpStoreSource's table name
func (*McpStoreSource) TableName() string {
	return TableNameMcpStoreSource
}
