// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMemoryEdge = "memory_edges"

// MemoryEdge mapped from table <memory_edges>
type MemoryEdge struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID      *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	FromMemoryID string  `gorm:"column:from_memory_id;type:TEXT;not null" json:"from_memory_id"`
	ToMemoryID   string  `gorm:"column:to_memory_id;type:TEXT;not null" json:"to_memory_id"`
	Relation     string  `gorm:"column:relation;type:TEXT;not null;default:'related'" json:"relation"`
	Weight       string  `gorm:"column:weight;type:TEXT;not null;default:'1'" json:"weight"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName MemoryEdge's table name
func (*MemoryEdge) TableName() string {
	return TableNameMemoryEdge
}
