// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMemoryProvider = "memory_providers"

// MemoryProvider mapped from table <memory_providers>
type MemoryProvider struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID   string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Name       string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Slug       string  `gorm:"column:slug;type:TEXT;not null" json:"slug"`
	Kind       string  `gorm:"column:kind;type:TEXT;not null" json:"kind"`
	ConfigJSON string  `gorm:"column:config_json;type:TEXT;not null;default:'{}'" json:"config_json"`
	SecretJSON string  `gorm:"column:secret_json;type:TEXT;not null;default:'{}'" json:"secret_json"`
	Enabled    bool    `gorm:"column:enabled;type:INTEGER;not null;default:1" json:"enabled"`
	IsDefault  bool    `gorm:"column:is_default;type:INTEGER;not null" json:"is_default"`
	Status     string  `gorm:"column:status;type:TEXT;not null;default:'ready'" json:"status"`
	LastError  *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt  string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName MemoryProvider's table name
func (*MemoryProvider) TableName() string {
	return TableNameMemoryProvider
}
