// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameModelUpstream = "model_upstreams"

// ModelUpstream mapped from table <model_upstreams>
type ModelUpstream struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID   string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Name       string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Slug       string  `gorm:"column:slug;type:TEXT;not null" json:"slug"`
	Protocol   string  `gorm:"column:protocol;type:TEXT;not null" json:"protocol"`
	ConfigJSON string  `gorm:"column:config_json;type:TEXT;not null;default:'{}'" json:"config_json"`
	Status     string  `gorm:"column:status;type:TEXT;not null;default:'ready'" json:"status"`
	LastError  *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt  string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName ModelUpstream's table name
func (*ModelUpstream) TableName() string {
	return TableNameModelUpstream
}
