// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameNetworkSecurityPolicy = "network_security_policies"

// NetworkSecurityPolicy mapped from table <network_security_policies>
type NetworkSecurityPolicy struct {
	ID                               *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID                         string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Scope                            string  `gorm:"column:scope;type:TEXT;not null;default:'tenant'" json:"scope"`
	Enabled                          bool    `gorm:"column:enabled;type:INTEGER;not null;default:1" json:"enabled"`
	ExposureEnabled                  bool    `gorm:"column:exposure_enabled;type:INTEGER;not null;default:1" json:"exposure_enabled"`
	DefaultTTLMinutes                int32   `gorm:"column:default_ttl_minutes;type:INTEGER;not null;default:60" json:"default_ttl_minutes"`
	MaxTTLMinutes                    int32   `gorm:"column:max_ttl_minutes;type:INTEGER;not null;default:1440" json:"max_ttl_minutes"`
	MaxActivePerAgent                int32   `gorm:"column:max_active_per_agent;type:INTEGER;not null;default:3" json:"max_active_per_agent"`
	MaxActivePerTenant               int32   `gorm:"column:max_active_per_tenant;type:INTEGER;not null;default:50" json:"max_active_per_tenant"`
	DeniedPortsJSON                  string  `gorm:"column:denied_ports_json;type:TEXT;not null;default:'[22,2375,2376,5432,6379,27017,5900,6080,9222,8787,7443]'" json:"denied_ports_json"`
	AllowDesktopExposure             bool    `gorm:"column:allow_desktop_exposure;type:INTEGER;not null" json:"allow_desktop_exposure"`
	AllowPublicExposure              bool    `gorm:"column:allow_public_exposure;type:INTEGER;not null;default:1" json:"allow_public_exposure"`
	AllowTcpExposure                 bool    `gorm:"column:allow_tcp_exposure;type:INTEGER;not null" json:"allow_tcp_exposure"`
	AgentsCanExpose                  bool    `gorm:"column:agents_can_expose;type:INTEGER;not null;default:1" json:"agents_can_expose"`
	RequireUserApproval              bool    `gorm:"column:require_user_approval;type:INTEGER;not null" json:"require_user_approval"`
	RequireTailscaleForRemoteRunners bool    `gorm:"column:require_tailscale_for_remote_runners;type:INTEGER;not null" json:"require_tailscale_for_remote_runners"`
	AuditRetentionDays               int32   `gorm:"column:audit_retention_days;type:INTEGER;not null;default:90" json:"audit_retention_days"`
	UpdatedBy                        *string `gorm:"column:updated_by;type:TEXT" json:"updated_by"`
	CreatedAt                        string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt                        string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName NetworkSecurityPolicy's table name
func (*NetworkSecurityPolicy) TableName() string {
	return TableNameNetworkSecurityPolicy
}
