// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameNetworkAuditLog = "network_audit_logs"

// NetworkAuditLog mapped from table <network_audit_logs>
type NetworkAuditLog struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID   string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	ActorType  string  `gorm:"column:actor_type;type:TEXT;not null" json:"actor_type"`
	ActorID    *string `gorm:"column:actor_id;type:TEXT" json:"actor_id"`
	Action     string  `gorm:"column:action;type:TEXT;not null" json:"action"`
	TargetType *string `gorm:"column:target_type;type:TEXT" json:"target_type"`
	TargetID   *string `gorm:"column:target_id;type:TEXT" json:"target_id"`
	DetailJSON string  `gorm:"column:detail_json;type:TEXT;not null;default:'{}'" json:"detail_json"`
	IP         *string `gorm:"column:ip;type:TEXT" json:"ip"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName NetworkAuditLog's table name
func (*NetworkAuditLog) TableName() string {
	return TableNameNetworkAuditLog
}
