// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameNetworkIntegration = "network_integrations"

// NetworkIntegration mapped from table <network_integrations>
type NetworkIntegration struct {
	ID             *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID       string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Kind           string  `gorm:"column:kind;type:TEXT;not null" json:"kind"`
	Status         string  `gorm:"column:status;type:TEXT;not null;default:'disconnected'" json:"status"`
	DisplayName    *string `gorm:"column:display_name;type:TEXT" json:"display_name"`
	CredentialsEnc string  `gorm:"column:credentials_enc;type:TEXT;not null;default:'{}'" json:"credentials_enc"`
	MetaJSON       string  `gorm:"column:meta_json;type:TEXT;not null;default:'{}'" json:"meta_json"`
	LastSyncAt     *string `gorm:"column:last_sync_at;type:TEXT" json:"last_sync_at"`
	LastError      *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt      string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt      string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName NetworkIntegration's table name
func (*NetworkIntegration) TableName() string {
	return TableNameNetworkIntegration
}
