// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOauthLoginState = "oauth_login_states"

// OauthLoginState mapped from table <oauth_login_states>
type OauthLoginState struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	Provider     string  `gorm:"column:provider;type:TEXT;not null" json:"provider"`
	CodeVerifier string  `gorm:"column:code_verifier;type:TEXT;not null" json:"code_verifier"`
	ExpiresAt    string  `gorm:"column:expires_at;type:TEXT;not null" json:"expires_at"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName OauthLoginState's table name
func (*OauthLoginState) TableName() string {
	return TableNameOauthLoginState
}
