// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOauthRefreshToken = "oauth_refresh_tokens"

// OauthRefreshToken mapped from table <oauth_refresh_tokens>
type OauthRefreshToken struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	FamilyID   string  `gorm:"column:family_id;type:TEXT;not null" json:"family_id"`
	TokenHash  string  `gorm:"column:token_hash;type:TEXT;not null" json:"token_hash"`
	ClientID   string  `gorm:"column:client_id;type:TEXT;not null" json:"client_id"`
	UserID     string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	TenantID   string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID    *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	Scope      string  `gorm:"column:scope;type:TEXT;not null" json:"scope"`
	Resource   *string `gorm:"column:resource;type:TEXT" json:"resource"`
	ExpiresAt  string  `gorm:"column:expires_at;type:TEXT;not null" json:"expires_at"`
	ConsumedAt *string `gorm:"column:consumed_at;type:TEXT" json:"consumed_at"`
	RevokedAt  *string `gorm:"column:revoked_at;type:TEXT" json:"revoked_at"`
	ReplacedBy *string `gorm:"column:replaced_by;type:TEXT" json:"replaced_by"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName OauthRefreshToken's table name
func (*OauthRefreshToken) TableName() string {
	return TableNameOauthRefreshToken
}
