// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameOauthIdentity = "oauth_identities"

// OauthIdentity mapped from table <oauth_identities>
type OauthIdentity struct {
	ID             *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	Provider       string  `gorm:"column:provider;type:TEXT;not null" json:"provider"`
	ProviderUserID string  `gorm:"column:provider_user_id;type:TEXT;not null" json:"provider_user_id"`
	UserID         string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	ProfileJSON    *string `gorm:"column:profile_json;type:TEXT" json:"profile_json"`
	CreatedAt      string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt      string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName OauthIdentity's table name
func (*OauthIdentity) TableName() string {
	return TableNameOauthIdentity
}
