// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePlatformSkillRepo = "platform_skill_repos"

// PlatformSkillRepo mapped from table <platform_skill_repos>
type PlatformSkillRepo struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	RepoKey      string  `gorm:"column:repo_key;type:TEXT;not null" json:"repo_key"`
	Provider     string  `gorm:"column:provider;type:TEXT;not null;default:'github'" json:"provider"`
	SourceJSON   string  `gorm:"column:source_json;type:TEXT;not null;default:'{}'" json:"source_json"`
	Ref          *string `gorm:"column:ref;type:TEXT" json:"ref"`
	Version      *string `gorm:"column:version;type:TEXT" json:"version"`
	UpstreamEtag *string `gorm:"column:upstream_etag;type:TEXT" json:"upstream_etag"`
	PackagesJSON string  `gorm:"column:packages_json;type:TEXT;not null;default:'[]'" json:"packages_json"`
	Partial      bool    `gorm:"column:partial;type:INTEGER;not null" json:"partial"`
	SkillCount   int32   `gorm:"column:skill_count;type:INTEGER;not null" json:"skill_count"`
	SizeBytes    int32   `gorm:"column:size_bytes;type:INTEGER;not null" json:"size_bytes"`
	WarningsJSON string  `gorm:"column:warnings_json;type:TEXT;not null;default:'[]'" json:"warnings_json"`
	CheckedAt    *string `gorm:"column:checked_at;type:TEXT" json:"checked_at"`
	FetchedAt    string  `gorm:"column:fetched_at;type:TEXT;not null" json:"fetched_at"`
	RefCount     int32   `gorm:"column:ref_count;type:INTEGER;not null" json:"ref_count"`
	LastError    *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName PlatformSkillRepo's table name
func (*PlatformSkillRepo) TableName() string {
	return TableNamePlatformSkillRepo
}
