// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePlatformServiceQuota = "platform_service_quotas"

// PlatformServiceQuota mapped from table <platform_service_quotas>
type PlatformServiceQuota struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	ScopeKey     string  `gorm:"column:scope_key;type:TEXT;not null" json:"scope_key"`
	ServiceKey   string  `gorm:"column:service_key;type:TEXT;not null" json:"service_key"`
	MonthlyLimit *int32  `gorm:"column:monthly_limit;type:INTEGER" json:"monthly_limit"`
	DailyLimit   *int32  `gorm:"column:daily_limit;type:INTEGER" json:"daily_limit"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName PlatformServiceQuota's table name
func (*PlatformServiceQuota) TableName() string {
	return TableNamePlatformServiceQuota
}
