// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePlatformServiceUsage = "platform_service_usage"

// PlatformServiceUsage mapped from table <platform_service_usage>
type PlatformServiceUsage struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	UserID       string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	ServiceKey   string  `gorm:"column:service_key;type:TEXT;not null" json:"service_key"`
	Period       string  `gorm:"column:period;type:TEXT;not null" json:"period"`
	RequestCount int32   `gorm:"column:request_count;type:INTEGER;not null" json:"request_count"`
	ErrorCount   int32   `gorm:"column:error_count;type:INTEGER;not null" json:"error_count"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName PlatformServiceUsage's table name
func (*PlatformServiceUsage) TableName() string {
	return TableNamePlatformServiceUsage
}
