// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePortExposure = "port_exposures"

// PortExposure mapped from table <port_exposures>
type PortExposure struct {
	ID            *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID      string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	AgentID       string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	RuntimeNodeID *string `gorm:"column:runtime_node_id;type:TEXT" json:"runtime_node_id"`
	Name          *string `gorm:"column:name;type:TEXT" json:"name"`
	Port          int32   `gorm:"column:port;type:INTEGER;not null" json:"port"`
	Protocol      string  `gorm:"column:protocol;type:TEXT;not null;default:'http'" json:"protocol"`
	Provider      string  `gorm:"column:provider;type:TEXT;not null" json:"provider"`
	Status        string  `gorm:"column:status;type:TEXT;not null;default:'starting'" json:"status"`
	PublicURL     *string `gorm:"column:public_url;type:TEXT" json:"public_url"`
	RelayHost     *string `gorm:"column:relay_host;type:TEXT" json:"relay_host"`
	RelayPort     *int32  `gorm:"column:relay_port;type:INTEGER" json:"relay_port"`
	IntegrationID *string `gorm:"column:integration_id;type:TEXT" json:"integration_id"`
	TTLMinutes    *int32  `gorm:"column:ttl_minutes;type:INTEGER" json:"ttl_minutes"`
	ExpiresAt     *string `gorm:"column:expires_at;type:TEXT" json:"expires_at"`
	LastError     *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedByType *string `gorm:"column:created_by_type;type:TEXT" json:"created_by_type"`
	CreatedByID   *string `gorm:"column:created_by_id;type:TEXT" json:"created_by_id"`
	StoppedAt     *string `gorm:"column:stopped_at;type:TEXT" json:"stopped_at"`
	CreatedAt     string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt     string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName PortExposure's table name
func (*PortExposure) TableName() string {
	return TableNamePortExposure
}
