// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProviderCatalog = "provider_catalog"

// ProviderCatalog mapped from table <provider_catalog>
type ProviderCatalog struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	Name         string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Kind         string  `gorm:"column:kind;type:TEXT;not null" json:"kind"`
	ManifestJSON string  `gorm:"column:manifest_json;type:TEXT;not null;default:'{}'" json:"manifest_json"`
	Enabled      bool    `gorm:"column:enabled;type:INTEGER;not null;default:1" json:"enabled"`
	UpdatedAt    string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName ProviderCatalog's table name
func (*ProviderCatalog) TableName() string {
	return TableNameProviderCatalog
}
