// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameRuntimeNode = "runtime_nodes"

// RuntimeNode mapped from table <runtime_nodes>
type RuntimeNode struct {
	ID               *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID         string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Name             string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Slug             string  `gorm:"column:slug;type:TEXT;not null" json:"slug"`
	Kind             string  `gorm:"column:kind;type:TEXT;not null;default:'computer'" json:"kind"`
	Status           string  `gorm:"column:status;type:TEXT;not null;default:'offline'" json:"status"`
	Endpoint         *string `gorm:"column:endpoint;type:TEXT" json:"endpoint"`
	CapabilitiesJSON string  `gorm:"column:capabilities_json;type:TEXT;not null;default:'{}'" json:"capabilities_json"`
	HostInfoJSON     string  `gorm:"column:host_info_json;type:TEXT;not null;default:'{}'" json:"host_info_json"`
	StorageRoot      string  `gorm:"column:storage_root;type:TEXT;not null" json:"storage_root"`
	AgentVersion     *string `gorm:"column:agent_version;type:TEXT" json:"agent_version"`
	LastSeenAt       *string `gorm:"column:last_seen_at;type:TEXT" json:"last_seen_at"`
	TokenHash        *string `gorm:"column:token_hash;type:TEXT" json:"token_hash"`
	LabelsJSON       string  `gorm:"column:labels_json;type:TEXT;not null;default:'{}'" json:"labels_json"`
	IsShared         bool    `gorm:"column:is_shared;type:INTEGER;not null" json:"is_shared"`
	CreatedByUserID  *string `gorm:"column:created_by_user_id;type:TEXT" json:"created_by_user_id"`
	CreatedAt        string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt        string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName RuntimeNode's table name
func (*RuntimeNode) TableName() string {
	return TableNameRuntimeNode
}
