// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSetting = "settings"

// Setting mapped from table <settings>
type Setting struct {
	ID       *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	OwnerKey string  `gorm:"column:owner_key;type:TEXT;not null" json:"owner_key"`
	Key      string  `gorm:"column:key;type:TEXT;not null" json:"key"`
	Value    string  `gorm:"column:value;type:TEXT;not null" json:"value"`
}

// TableName Setting's table name
func (*Setting) TableName() string {
	return TableNameSetting
}
