// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSkill = "skills"

// Skill mapped from table <skills>
type Skill struct {
	ID          *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID    string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Name        string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Title       string  `gorm:"column:title;type:TEXT;not null" json:"title"`
	Description string  `gorm:"column:description;type:TEXT;not null" json:"description"`
	Version     *string `gorm:"column:version;type:TEXT" json:"version"`
	Builtin     bool    `gorm:"column:builtin;type:INTEGER;not null" json:"builtin"`
	SourceJSON  string  `gorm:"column:source_json;type:TEXT;not null;default:'{}'" json:"source_json"`
	Homepage    *string `gorm:"column:homepage;type:TEXT" json:"homepage"`
	License     *string `gorm:"column:license;type:TEXT" json:"license"`
	FilesJSON   string  `gorm:"column:files_json;type:TEXT;not null;default:'[]'" json:"files_json"`
	FileCount   int32   `gorm:"column:file_count;type:INTEGER;not null" json:"file_count"`
	SizeBytes   int32   `gorm:"column:size_bytes;type:INTEGER;not null" json:"size_bytes"`
	RepoKey     *string `gorm:"column:repo_key;type:TEXT" json:"repo_key"`
	AutoUpdate  bool    `gorm:"column:auto_update;type:INTEGER;not null;default:1" json:"auto_update"`
	CreatedAt   string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt   string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName Skill's table name
func (*Skill) TableName() string {
	return TableNameSkill
}
