// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSpace = "spaces"

// Space mapped from table <spaces>
type Space struct {
	ID              *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID        string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Name            string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Slug            string  `gorm:"column:slug;type:TEXT;not null" json:"slug"`
	Description     *string `gorm:"column:description;type:TEXT" json:"description"`
	EnableComputer  bool    `gorm:"column:enable_computer;type:INTEGER;not null" json:"enable_computer"`
	WorkspaceImage  *string `gorm:"column:workspace_image;type:TEXT" json:"workspace_image"`
	RuntimeNodeID   *string `gorm:"column:runtime_node_id;type:TEXT" json:"runtime_node_id"`
	WorkspaceKind   string  `gorm:"column:workspace_kind;type:TEXT;not null;default:'local'" json:"workspace_kind"`
	WorkspaceStatus string  `gorm:"column:workspace_status;type:TEXT;not null;default:'ready'" json:"workspace_status"`
	ConfigJSON      string  `gorm:"column:config_json;type:TEXT;not null;default:'{}'" json:"config_json"`
	LastError       *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	CreatedAt       string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt       string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName Space's table name
func (*Space) TableName() string {
	return TableNameSpace
}
