// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameStoreCatalogEntry = "store_catalog_entries"

// StoreCatalogEntry mapped from table <store_catalog_entries>
type StoreCatalogEntry struct {
	ID          *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID    *string `gorm:"column:tenant_id;type:TEXT" json:"tenant_id"`
	SourceID    string  `gorm:"column:source_id;type:TEXT;not null" json:"source_id"`
	Kind        string  `gorm:"column:kind;type:TEXT;not null" json:"kind"`
	Ref         string  `gorm:"column:ref;type:TEXT;not null" json:"ref"`
	Name        string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Description string  `gorm:"column:description;type:TEXT;not null" json:"description"`
	MetaJSON    string  `gorm:"column:meta_json;type:TEXT;not null;default:'{}'" json:"meta_json"`
	UpdatedAt   string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName StoreCatalogEntry's table name
func (*StoreCatalogEntry) TableName() string {
	return TableNameStoreCatalogEntry
}
