// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTenantDomain = "tenant_domains"

// TenantDomain mapped from table <tenant_domains>
type TenantDomain struct {
	ID                *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID          string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Domain            string  `gorm:"column:domain;type:TEXT;not null" json:"domain"`
	JoinMode          string  `gorm:"column:join_mode;type:TEXT;not null;default:'invite_only'" json:"join_mode"`
	VerificationToken string  `gorm:"column:verification_token;type:TEXT;not null" json:"verification_token"`
	VerifiedAt        *string `gorm:"column:verified_at;type:TEXT" json:"verified_at"`
	CreatedAt         string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt         string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName TenantDomain's table name
func (*TenantDomain) TableName() string {
	return TableNameTenantDomain
}
