// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTenantInvite = "tenant_invites"

// TenantInvite mapped from table <tenant_invites>
type TenantInvite struct {
	ID         *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID   string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Email      string  `gorm:"column:email;type:TEXT;not null" json:"email"`
	Role       string  `gorm:"column:role;type:TEXT;not null" json:"role"`
	TokenHash  string  `gorm:"column:token_hash;type:TEXT;not null" json:"token_hash"`
	ExpiresAt  string  `gorm:"column:expires_at;type:TEXT;not null" json:"expires_at"`
	AcceptedAt *string `gorm:"column:accepted_at;type:TEXT" json:"accepted_at"`
	InvitedBy  *string `gorm:"column:invited_by;type:TEXT" json:"invited_by"`
	CreatedAt  string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName TenantInvite's table name
func (*TenantInvite) TableName() string {
	return TableNameTenantInvite
}
