// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTenantScimToken = "tenant_scim_tokens"

// TenantScimToken mapped from table <tenant_scim_tokens>
type TenantScimToken struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Name         string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	TokenHash    string  `gorm:"column:token_hash;type:TEXT;not null" json:"token_hash"`
	TokenPrefix  string  `gorm:"column:token_prefix;type:TEXT;not null" json:"token_prefix"`
	GroupRoleMap string  `gorm:"column:group_role_map;type:TEXT;not null;default:'{}'" json:"group_role_map"`
	LastUsedAt   *string `gorm:"column:last_used_at;type:TEXT" json:"last_used_at"`
	RevokedAt    *string `gorm:"column:revoked_at;type:TEXT" json:"revoked_at"`
	CreatedAt    string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName TenantScimToken's table name
func (*TenantScimToken) TableName() string {
	return TableNameTenantScimToken
}
