// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTenantMembership = "tenant_memberships"

// TenantMembership mapped from table <tenant_memberships>
type TenantMembership struct {
	ID        *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID  string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	UserID    string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	Role      string  `gorm:"column:role;type:TEXT;not null" json:"role"`
	Status    string  `gorm:"column:status;type:TEXT;not null;default:'active'" json:"status"`
	CreatedAt string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName TenantMembership's table name
func (*TenantMembership) TableName() string {
	return TableNameTenantMembership
}
