// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUpstreamOauthClient = "upstream_oauth_clients"

// UpstreamOauthClient mapped from table <upstream_oauth_clients>
type UpstreamOauthClient struct {
	ID                   *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID             string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	McpURL               string  `gorm:"column:mcp_url;type:TEXT;not null" json:"mcp_url"`
	Host                 string  `gorm:"column:host;type:TEXT;not null" json:"host"`
	ClientID             string  `gorm:"column:client_id;type:TEXT;not null" json:"client_id"`
	SecretEnc            *string `gorm:"column:secret_enc;type:TEXT" json:"secret_enc"`
	ClientName           string  `gorm:"column:client_name;type:TEXT;not null" json:"client_name"`
	Source               string  `gorm:"column:source;type:TEXT;not null" json:"source"`
	RegistrationEndpoint *string `gorm:"column:registration_endpoint;type:TEXT" json:"registration_endpoint"`
	Scope                string  `gorm:"column:scope;type:TEXT;not null" json:"scope"`
	InstanceID           *string `gorm:"column:instance_id;type:TEXT" json:"instance_id"`
	CreatedAt            string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt            string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName UpstreamOauthClient's table name
func (*UpstreamOauthClient) TableName() string {
	return TableNameUpstreamOauthClient
}
