// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUpstreamModel = "upstream_models"

// UpstreamModel mapped from table <upstream_models>
type UpstreamModel struct {
	ID             *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID       string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	UpstreamID     string  `gorm:"column:upstream_id;type:TEXT;not null" json:"upstream_id"`
	NativeModel    string  `gorm:"column:native_model;type:TEXT;not null" json:"native_model"`
	CanonicalModel string  `gorm:"column:canonical_model;type:TEXT;not null" json:"canonical_model"`
	DisplayName    *string `gorm:"column:display_name;type:TEXT" json:"display_name"`
	Capability     string  `gorm:"column:capability;type:TEXT;not null" json:"capability"`
	Weight         string  `gorm:"column:weight;type:TEXT;not null;default:'100'" json:"weight"`
	IsDefault      bool    `gorm:"column:is_default;type:INTEGER;not null" json:"is_default"`
	OptionsJSON    string  `gorm:"column:options_json;type:TEXT;not null;default:'{}'" json:"options_json"`
	MetaJSON       string  `gorm:"column:meta_json;type:TEXT;not null;default:'{}'" json:"meta_json"`
	Status         string  `gorm:"column:status;type:TEXT;not null;default:'ready'" json:"status"`
	LastError      *string `gorm:"column:last_error;type:TEXT" json:"last_error"`
	SyncedAt       *string `gorm:"column:synced_at;type:TEXT" json:"synced_at"`
	CreatedAt      string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
	UpdatedAt      string  `gorm:"column:updated_at;type:TEXT;not null" json:"updated_at"`
}

// TableName UpstreamModel's table name
func (*UpstreamModel) TableName() string {
	return TableNameUpstreamModel
}
