// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserSession = "user_sessions"

// UserSession mapped from table <user_sessions>
type UserSession struct {
	ID              *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	UserID          string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	TenantID        string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	Email           string  `gorm:"column:email;type:TEXT;not null" json:"email"`
	Role            string  `gorm:"column:role;type:TEXT;not null" json:"role"`
	IsPlatformAdmin bool    `gorm:"column:is_platform_admin;type:INTEGER;not null" json:"is_platform_admin"`
	TokenHash       string  `gorm:"column:token_hash;type:TEXT;not null" json:"token_hash"`
	IP              *string `gorm:"column:ip;type:TEXT" json:"ip"`
	UserAgent       *string `gorm:"column:user_agent;type:TEXT" json:"user_agent"`
	ExpiresAt       string  `gorm:"column:expires_at;type:TEXT;not null" json:"expires_at"`
	LastSeenAt      string  `gorm:"column:last_seen_at;type:TEXT;not null" json:"last_seen_at"`
	RevokedAt       *string `gorm:"column:revoked_at;type:TEXT" json:"revoked_at"`
	CreatedAt       string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName UserSession's table name
func (*UserSession) TableName() string {
	return TableNameUserSession
}
