// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserRecoveryCode = "user_recovery_codes"

// UserRecoveryCode mapped from table <user_recovery_codes>
type UserRecoveryCode struct {
	ID        *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	UserID    string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	CodeHash  string  `gorm:"column:code_hash;type:TEXT;not null" json:"code_hash"`
	UsedAt    *string `gorm:"column:used_at;type:TEXT" json:"used_at"`
	CreatedAt string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName UserRecoveryCode's table name
func (*UserRecoveryCode) TableName() string {
	return TableNameUserRecoveryCode
}
