// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserTotp = "user_totp"

// UserTotp mapped from table <user_totp>
type UserTotp struct {
	UserID    *string `gorm:"column:user_id;type:TEXT;primaryKey" json:"user_id"`
	SecretEnc string  `gorm:"column:secret_enc;type:TEXT;not null" json:"secret_enc"`
	EnabledAt *string `gorm:"column:enabled_at;type:TEXT" json:"enabled_at"`
	CreatedAt string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName UserTotp's table name
func (*UserTotp) TableName() string {
	return TableNameUserTotp
}
