// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserUsageDaily = "user_usage_daily"

// UserUsageDaily mapped from table <user_usage_daily>
type UserUsageDaily struct {
	ID              *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID        string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	UserID          string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	Day             string  `gorm:"column:day;type:TEXT;not null" json:"day"`
	Logins          int32   `gorm:"column:logins;type:INTEGER;not null" json:"logins"`
	SessionsStarted int32   `gorm:"column:sessions_started;type:INTEGER;not null" json:"sessions_started"`
	RunsOk          int32   `gorm:"column:runs_ok;type:INTEGER;not null" json:"runs_ok"`
	RunsError       int32   `gorm:"column:runs_error;type:INTEGER;not null" json:"runs_error"`
	ToolCalls       int32   `gorm:"column:tool_calls;type:INTEGER;not null" json:"tool_calls"`
	ToolErrors      int32   `gorm:"column:tool_errors;type:INTEGER;not null" json:"tool_errors"`
	DurationMs      int32   `gorm:"column:duration_ms;type:INTEGER;not null" json:"duration_ms"`
	LastSeenAt      *string `gorm:"column:last_seen_at;type:TEXT" json:"last_seen_at"`
}

// TableName UserUsageDaily's table name
func (*UserUsageDaily) TableName() string {
	return TableNameUserUsageDaily
}
