// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserUsageEvent = "user_usage_events"

// UserUsageEvent mapped from table <user_usage_events>
type UserUsageEvent struct {
	ID           *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID     string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	UserID       string  `gorm:"column:user_id;type:TEXT;not null" json:"user_id"`
	Category     string  `gorm:"column:category;type:TEXT;not null" json:"category"`
	Units        int32   `gorm:"column:units;type:INTEGER;not null" json:"units"`
	DetailJSON   string  `gorm:"column:detail_json;type:TEXT;not null;default:'{}'" json:"detail_json"`
	OccurredAt   string  `gorm:"column:occurred_at;type:TEXT;not null" json:"occurred_at"`
	ActorKind    string  `gorm:"column:actor_kind;type:TEXT;not null;default:'user'" json:"actor_kind"`
	Action       string  `gorm:"column:action;type:TEXT;not null;default:'tool_called'" json:"action"`
	Status       string  `gorm:"column:status;type:TEXT;not null;default:'ok'" json:"status"`
	DurationMs   int32   `gorm:"column:duration_ms;type:INTEGER;not null" json:"duration_ms"`
	AgentID      *string `gorm:"column:agent_id;type:TEXT" json:"agent_id"`
	SessionID    *string `gorm:"column:session_id;type:TEXT" json:"session_id"`
	ResourceKind *string `gorm:"column:resource_kind;type:TEXT" json:"resource_kind"`
	ResourceID   *string `gorm:"column:resource_id;type:TEXT" json:"resource_id"`
	Summary      string  `gorm:"column:summary;type:TEXT;not null" json:"summary"`
	CreatedAt    *string `gorm:"column:created_at;type:TEXT" json:"created_at"`
}

// TableName UserUsageEvent's table name
func (*UserUsageEvent) TableName() string {
	return TableNameUserUsageEvent
}
