// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameZakurabotInteraction = "zakurabot_interactions"

// ZakurabotInteraction mapped from table <zakurabot_interactions>
type ZakurabotInteraction struct {
	ID              *string `gorm:"column:id;type:TEXT;primaryKey" json:"id"`
	TenantID        string  `gorm:"column:tenant_id;type:TEXT;not null" json:"tenant_id"`
	DeviceID        string  `gorm:"column:device_id;type:TEXT;not null" json:"device_id"`
	BindingID       string  `gorm:"column:binding_id;type:TEXT;not null" json:"binding_id"`
	AgentID         string  `gorm:"column:agent_id;type:TEXT;not null" json:"agent_id"`
	SessionID       string  `gorm:"column:session_id;type:TEXT;not null" json:"session_id"`
	RunID           *string `gorm:"column:run_id;type:TEXT" json:"run_id"`
	SourceSessionID string  `gorm:"column:source_session_id;type:TEXT;not null" json:"source_session_id"`
	SourceRunID     *string `gorm:"column:source_run_id;type:TEXT" json:"source_run_id"`
	RequestID       string  `gorm:"column:request_id;type:TEXT;not null" json:"request_id"`
	Type            string  `gorm:"column:type;type:TEXT;not null" json:"type"`
	PayloadJSON     string  `gorm:"column:payload_json;type:TEXT;not null" json:"payload_json"`
	ReplyTo         *string `gorm:"column:reply_to;type:TEXT" json:"reply_to"`
	Status          string  `gorm:"column:status;type:TEXT;not null;default:'pending'" json:"status"`
	ClaimedAt       *string `gorm:"column:claimed_at;type:TEXT" json:"claimed_at"`
	EventSeq        int32   `gorm:"column:event_seq;type:INTEGER;not null" json:"event_seq"`
	CreatedAt       string  `gorm:"column:created_at;type:TEXT;not null" json:"created_at"`
}

// TableName ZakurabotInteraction's table name
func (*ZakurabotInteraction) TableName() string {
	return TableNameZakurabotInteraction
}
